"""Dataset B — a new output *format* on known content (the "alien" format).

Source: CoNLL-2003 NER (PER / ORG / LOC / MISC).  The target is derived from the gold
annotations by deterministic rules — never generated by an LLM — so ground truth is exact.

Two difficulty levels, both derived by deterministic rules and checked exactly.

``copy`` (level 1) — the original schema: entities copied verbatim, in order of appearance.

    <<alien>>
    {"qzx_pers": [...], "qzx_org": [...], "qzx_loc": [...], "qzx_misc": [...], "qzx_n": N}
    <</alien>>

``transform`` (level 2, default) — same tags and keys, but the content must be *transformed*:

    * person names are rewritten ``LAST, First`` with the family name upper-cased;
    * every list is sorted alphabetically (case-insensitive), not in order of appearance;
    * ``qzx_n`` is spelled out in English words ("three", not 3);
    * a final key ``qzx_sig`` holds the initials of all entities, in JSON order, upper-cased.

Why: level 1 is essentially a *copy* operation — attention heads do it natively, and a rank-16
LoRA reaches 99.6 % parsing in ~130 steps, which saturates the task and leaves nothing to
discriminate between adaptation subspaces.  Level 2 keeps the task purely formal (known content,
rule-derived target, exact checker) but requires reordering, sorting, casing and a lookup, none
of which is a copy.  The difficulty is a *knob*, not a fix: report which level was used.
Loss is computed on the answer only (see ``loaders.py``).

The strict checker is the main metric (parsing success rate).  Sanity check at t=0: the
un-adapted model must score < 10 % parsed, otherwise the format is already known and the
keys/tags must be changed.
"""
from __future__ import annotations

import json
import random
import re
from collections import Counter, OrderedDict
from pathlib import Path

KEYS: tuple[str, ...] = ("qzx_pers", "qzx_org", "qzx_loc", "qzx_misc", "qzx_n")
KEYS_HARD: tuple[str, ...] = KEYS + ("qzx_sig",)
VARIANTS: tuple[str, ...] = ("copy", "transform")

_UNITS = ("zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
          "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
          "nineteen")
_TENS = ("", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety")


def spell_number(n: int) -> str:
    """0-99 in English words; two-digit numbers hyphenated ("twenty-three")."""
    if n < 20:
        return _UNITS[n]
    tens, unit = divmod(n, 10)
    return _TENS[tens] + ("-" + _UNITS[unit] if unit else "")


def rewrite_person(name: str) -> str:
    """``John Smith`` -> ``SMITH, John``; a single token is just upper-cased."""
    parts = name.split()
    if len(parts) == 1:
        return parts[0].upper()
    return f"{parts[-1].upper()}, {' '.join(parts[:-1])}"


def signature(values: list[str]) -> str:
    """Initials of every entity, in JSON order, upper-cased (requires attending to all of them)."""
    return "".join(v.strip()[0].upper() for v in values if v.strip())
TAG_OPEN, TAG_CLOSE = "<<alien>>", "<</alien>>"
LABEL_TO_KEY = {"PER": "qzx_pers", "ORG": "qzx_org", "LOC": "qzx_loc", "MISC": "qzx_misc"}

# CoNLL-2003 label ids (identical in the Parquet mirror and the historical script repos)
CONLL_LABELS: tuple[str, ...] = ("O", "B-PER", "I-PER", "B-ORG", "I-ORG", "B-LOC", "I-LOC", "B-MISC", "I-MISC")

PROMPT = "Extract the entities from the text below and answer in the alien format.\nText: {text}\nAnswer:"

_ALIEN_RE = re.compile(r"^" + re.escape(TAG_OPEN) + r"\n(.*)\n" + re.escape(TAG_CLOSE) + r"$", re.S)
_KEY_ORDER_RE = re.compile(r'"(qzx_[a-z]+)"\s*:')


# --------------------------------------------------------------------------- #
# Target construction
# --------------------------------------------------------------------------- #
def spans_from_bio(tokens: list[str], tags: list[str]) -> list[tuple[str, str]]:
    """BIO tags -> [(label, "entity text"), ...] in order of appearance.  Tolerates I- without B-."""
    spans: list[tuple[str, list[str]]] = []
    cur_label: str | None = None
    for tok, tag in zip(tokens, tags):
        if tag == "O":
            cur_label = None
            continue
        prefix, label = tag.split("-", 1)
        if prefix == "B" or cur_label != label:
            spans.append((label, [tok]))
            cur_label = label
        else:
            spans[-1][1].append(tok)
    return [(lab, " ".join(toks)) for lab, toks in spans]


def alien_dict(tokens: list[str], tags: list[str], variant: str = "transform") -> "OrderedDict[str, object]":
    """Target dict for one sentence.  ``copy``: verbatim, in order of appearance.
    ``transform``: persons rewritten, lists sorted, count spelled out, signature appended."""
    if variant not in VARIANTS:
        raise ValueError(f"variant must be one of {VARIANTS}")
    d: "OrderedDict[str, object]" = OrderedDict((k, []) for k in KEYS[:-1])
    n = 0
    for label, text in spans_from_bio(tokens, tags):
        value = rewrite_person(text) if (variant == "transform" and label == "PER") else text
        d[LABEL_TO_KEY[label]].append(value)
        n += 1
    if variant == "transform":
        for k in KEYS[:-1]:
            d[k] = sorted(d[k], key=str.lower)
        d["qzx_n"] = spell_number(n)
        d["qzx_sig"] = signature([v for k in KEYS[:-1] for v in d[k]])
    else:
        d["qzx_n"] = n
    return d


def alien_string(d: "OrderedDict[str, object]") -> str:
    body = json.dumps(d, ensure_ascii=False, separators=(", ", ": "))
    return f"{TAG_OPEN}\n{body}\n{TAG_CLOSE}"


def detokenize(tokens: list[str]) -> str:
    """Join CoNLL tokens into readable text (no space before punctuation)."""
    out = ""
    for t in tokens:
        if out and (t in ",.;:!?)']" or t.startswith("'")):
            out += t
        elif out and out[-1] in "($":
            out += t
        else:
            out += (" " if out else "") + t
    return out


def build_example(tokens: list[str], tag_ids: list[int], labels: tuple[str, ...] = CONLL_LABELS,
                  variant: str = "transform") -> dict:
    tags = [labels[i] for i in tag_ids]
    text = detokenize(tokens)
    gold = alien_dict(tokens, tags, variant)
    n_ent = sum(len(gold[k]) for k in KEYS[:-1])
    return {"text": text, "prompt": PROMPT.format(text=text), "target": alien_string(gold),
            "gold": dict(gold), "variant": variant, "n_entities": n_ent}


# --------------------------------------------------------------------------- #
# Checker
# --------------------------------------------------------------------------- #
def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", s.strip().lower())


def _f1_counts(pred: list, gold: list) -> tuple[int, int, int]:
    """(true positives, |pred|, |gold|) as multisets of normalised strings."""
    p = Counter(_norm(x) for x in pred if isinstance(x, str))
    g = Counter(_norm(x) for x in gold)
    return sum((p & g).values()), sum(p.values()), sum(g.values())


def _f1_from_counts(tp: int, n_pred: int, n_gold: int) -> float:
    if n_pred == 0 and n_gold == 0:
        return 1.0
    if tp == 0:
        return 0.0
    prec, rec = tp / n_pred, tp / n_gold
    return 2 * prec * rec / (prec + rec)


def _f1(pred: list, gold: list) -> float:
    p = Counter(_norm(x) for x in pred if isinstance(x, str))
    g = Counter(_norm(x) for x in gold)
    if not p and not g:
        return 1.0
    tp = sum((p & g).values())
    prec = tp / max(1, sum(p.values()))
    rec = tp / max(1, sum(g.values()))
    return 0.0 if tp == 0 else 2 * prec * rec / (prec + rec)


def check_alien(output: str, gold: dict) -> dict:
    """Strict check of a generated string against the gold alien dict.

    The expected key set is inferred from ``gold`` (5 keys for ``copy``, 6 for ``transform``), so the
    same checker serves both levels.  ``parsed`` requires: exact tags, valid single-line JSON, exactly
    the expected keys in order, list-of-str values, and a count field that matches the number of listed
    entities (an int for ``copy``, its English spelling for ``transform``).  For ``transform`` the
    signature must also match the initials of the listed entities: it is reported separately
    (``sig_ok``) and required for ``parsed``, so that a model producing a perfect list but a wrong
    signature is not credited.
    """
    hard = "qzx_sig" in gold
    keys = KEYS_HARD if hard else KEYS
    res = {"parsed": False, "keys_ok": False, "n_ok": False, "sig_ok": not hard, "order_ok": not hard,
           "exact": False, "field_f1": {k: 0.0 for k in KEYS[:-1]}, "f1_mean": 0.0, "f1_micro": 0.0,
           "f1_macro": 0.0, "n_gold_entities": sum(len(gold.get(k, [])) for k in KEYS[:-1])}
    s = output.strip()
    m = _ALIEN_RE.match(s)
    if m is None:
        return res
    body = m.group(1)
    if "\n" in body:
        return res
    try:
        d = json.loads(body, object_pairs_hook=OrderedDict)
    except json.JSONDecodeError:
        return res
    if not isinstance(d, OrderedDict):
        return res
    raw_order = _KEY_ORDER_RE.findall(body)
    keys_ok = list(d.keys()) == list(keys) and raw_order == list(keys)
    res["keys_ok"] = keys_ok
    lists_ok = all(isinstance(d.get(k), list) and all(isinstance(x, str) for x in d[k]) for k in KEYS[:-1])
    listed = [v for k in KEYS[:-1] for v in d.get(k, [])] if lists_ok else []
    if hard:
        n_ok = lists_ok and d.get("qzx_n") == spell_number(len(listed))
        res["sig_ok"] = lists_ok and isinstance(d.get("qzx_sig"), str) and d["qzx_sig"] == signature(listed)
    else:
        n_ok = (lists_ok and isinstance(d.get("qzx_n"), int) and not isinstance(d.get("qzx_n"), bool)
                and d["qzx_n"] == len(listed))
    res["n_ok"] = bool(n_ok)
    if hard and lists_ok:
        res["order_ok"] = all(list(d.get(k, [])) == sorted(d.get(k, []), key=str.lower)
                              for k in KEYS[:-1])
    # `parsed` = the output obeys EVERY stated rule of the format, ordering included. Before
    # 2026-09-11 the sort was computed but not required, so a model emitting unsorted lists scored as
    # valid; numbers produced before that date used the looser definition and are not comparable.
    res["parsed"] = bool(keys_ok and lists_ok and n_ok and res["sig_ok"] and res["order_ok"])
    if lists_ok:
        tp = n_pred = n_gold = 0
        for k in KEYS[:-1]:
            res["field_f1"][k] = _f1(d.get(k, []), gold.get(k, []))
            a, b, c = _f1_counts(d.get(k, []), gold.get(k, []))
            tp, n_pred, n_gold = tp + a, n_pred + b, n_gold + c
        # macro over the four fields: kept for continuity, but INFLATED — a field that is empty in
        # both prediction and gold scores 1.0, so a sentence with one entity has a floor of 0.75.
        res["f1_macro"] = sum(res["field_f1"].values()) / len(KEYS[:-1])
        # micro over the entities themselves: no free points for empty fields. This is the metric
        # to report; it is the one with resolution.
        res["f1_micro"] = _f1_from_counts(tp, n_pred, n_gold)
        res["f1_mean"] = res["f1_micro"]
        res["n_gold_entities"] = n_gold
        # `parsed` says nothing about content: an output with every list empty, "qzx_n": "zero" and an
        # empty signature is internally coherent and scores parsed=True with F1=0. Since the data keep
        # only sentences with >= 3 entities, such an answer is wrong on every item, so a metric that
        # rewards it can be maxed by learning the shell alone. `exact` is the content-aware metric:
        # every rule obeyed AND every entity right.
        res["exact"] = bool(res["parsed"] and res["f1_micro"] >= 1.0 - 1e-9)
    return res


# --------------------------------------------------------------------------- #
# Dataset construction (needs `datasets`, internet or HF cache)
# --------------------------------------------------------------------------- #
SOURCES: tuple[str, ...] = (
    # Parquet, viewer enabled, same tagset and splits as the original: works with datasets >= 4.
    "tomaarsen/conll2003",
    # Script-based repos: only usable with datasets < 4 (kept as fallbacks for pinned environments).
    "eriktks/conll2003",
    "conll2003",
)


def _datasets_major() -> int:
    import datasets

    return int(datasets.__version__.split(".")[0])


def _label_names(ds) -> tuple[str, ...] | None:
    """NER label names if the split carries a ClassLabel feature, else None (plain int columns)."""
    feat = ds["train"].features.get("ner_tags")
    names = getattr(getattr(feat, "feature", None), "names", None)
    return tuple(names) if names else None


def load_conll(hf_name: str | None = None, verbose: bool = True):
    """Load CoNLL-2003 from the first working source.  Returns (dataset_dict, label_names, source).

    ``datasets`` >= 4.0 removed loading scripts *and* the ``trust_remote_code`` argument (passing it
    now raises), so script-based repos such as ``eriktks/conll2003`` fail there with
    "Dataset scripts are no longer supported".  The Parquet mirror is therefore tried first.
    """
    from datasets import load_dataset

    major = _datasets_major()
    candidates = [hf_name] if hf_name else list(SOURCES)
    errors: list[str] = []
    for name in candidates:
        kwargs_list = [{}] if major >= 4 else [{}, {"trust_remote_code": True}]
        for kw in kwargs_list:
            try:
                ds = load_dataset(name, **kw)
            except Exception as e:  # noqa: BLE001
                errors.append(f"{name}{' +trust_remote_code' if kw else ''}: {type(e).__name__}: {str(e)[:160]}")
                continue
            if not {"train", "validation", "test"} <= set(ds):
                errors.append(f"{name}: unexpected splits {sorted(ds)}")
                break
            names = _label_names(ds)
            if names is not None and tuple(names) != CONLL_LABELS:
                errors.append(f"{name}: unexpected label set {names}")
                break
            if verbose:
                print(f"[format] CoNLL-2003 loaded from {name!r} (datasets {major}.x, "
                      f"labels {'from features' if names else 'assumed ' + str(CONLL_LABELS)})")
            return ds, (names or CONLL_LABELS), name
    raise RuntimeError(
        "could not load CoNLL-2003 from any source.\n  " + "\n  ".join(errors) +
        "\nFixes: (a) use the Parquet mirror (default, needs network access to huggingface.co), "
        "(b) pin `datasets<4` to use the script-based repos, or "
        "(c) build offline from the original files with build_format_dataset(..., conll_dir=<dir>) "
        "where <dir> holds eng.train / eng.testa / eng.testb in CoNLL column format."
    )


def read_conll_file(path: str | Path) -> list[dict]:
    """Parse a CoNLL-2003 column file (word POS chunk NER per line, blank line between sentences).

    Offline path: no Hub, no `datasets`.  -DOCSTART- lines are skipped, IOB1 is converted to IOB2
    so that the tags match the Hub version."""
    sents: list[dict] = []
    toks: list[str] = []
    tags: list[str] = []

    def flush():
        if toks:
            iob2, prev = [], "O"
            for t in tags:  # IOB1 -> IOB2: an I- opening a new span becomes B-
                if t == "O":
                    iob2.append(t)
                else:
                    pre, lab = t.split("-", 1)
                    prev_lab = prev.split("-", 1)[1] if prev != "O" else None
                    iob2.append(f"B-{lab}" if (pre == "I" and prev_lab != lab) else t)
                prev = iob2[-1]
            sents.append({"tokens": list(toks), "ner_tags": [CONLL_LABELS.index(t) for t in iob2]})
        toks.clear()
        tags.clear()

    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("-DOCSTART-"):
                flush()
                continue
            parts = line.split()
            toks.append(parts[0])
            tags.append(parts[-1])
    flush()
    return sents


def build_format_dataset(
    out_dir: str | Path,
    n_train: int = 5000,
    n_val: int = 500,
    n_test: int = 1000,
    seed: int = 0,
    hf_name: str | None = None,
    min_entities: int = 3,
    max_tokens: int = 60,
    conll_dir: str | Path | None = None,
    variant: str = "transform",
) -> dict[str, int]:
    """Write train/val/test jsonl with fields text, prompt, target, gold.

    Source: the Hub (Parquet mirror first) or, with ``conll_dir``, the original column files
    (eng.train / eng.testa / eng.testb) for machines without network access."""
    rng_seed = seed

    def convert(rows, n, labels):
        out = []
        for ex in rows:
            toks, tags = ex["tokens"], ex["ner_tags"]
            if len(toks) > max_tokens or len(toks) < 3:
                continue
            e = build_example(toks, tags, labels, variant)
            n_ent = sum(len(e["gold"][k]) for k in KEYS[:-1])  # qzx_n is spelled out in the hard variant
            if n_ent < min_entities:
                continue
            out.append(e)
        rng = random.Random(rng_seed)
        rng.shuffle(out)
        return out[:n]

    if conll_dir:
        d = Path(conll_dir)
        files = {"train": ["eng.train", "train.txt"], "validation": ["eng.testa", "valid.txt", "dev.txt"],
                 "test": ["eng.testb", "test.txt"]}
        raw = {}
        for split, names in files.items():
            hit = next((d / n for n in names if (d / n).exists()), None)
            if hit is None:
                raise FileNotFoundError(f"{split}: none of {names} found in {d}")
            raw[split] = read_conll_file(hit)
        labels, source = CONLL_LABELS, str(d)
    else:
        ds, labels, source = load_conll(hf_name)
        raw = {k: ds[k] for k in ("train", "validation", "test")}

    train = convert(raw["train"], n_train, labels)
    val = convert(raw["validation"], n_val, labels)
    test = convert(raw["test"], n_test, labels)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for name, rows in (("train", train), ("val", val), ("test", test)):
        with open(out / f"{name}.jsonl", "w", encoding="utf-8") as f:
            for r in rows:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")
    import statistics

    ents = [r["n_entities"] for r in train]
    stats = {"train": len(train), "val": len(val), "test": len(test), "source": source, "variant": variant,
             "min_entities": min_entities,
             "entities_per_sentence_mean": round(statistics.mean(ents), 2) if ents else 0,
             "entities_per_sentence_max": max(ents) if ents else 0}
    with open(out / "stats.json", "w") as f:
        json.dump(stats, f, indent=2)
    return stats


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser(description="Dataset B: alien format on CoNLL-2003")
    ap.add_argument("out_dir")
    ap.add_argument("--n_train", type=int, default=5000)
    ap.add_argument("--n_val", type=int, default=500)
    ap.add_argument("--n_test", type=int, default=1000)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--hf_name", default=None, help="force one Hub repo instead of trying SOURCES in order")
    ap.add_argument("--conll_dir", default=None, help="offline: directory with eng.train / eng.testa / eng.testb")
    ap.add_argument("--min_entities", type=int, default=3,
                    help="sentences with fewer entities are dropped: sorting and the signature are "
                         "trivial on 1-entity sentences, which is what kept the task saturated")
    ap.add_argument("--variant", default="transform", choices=list(VARIANTS),
                    help="copy = verbatim (saturates fast); transform = sorted + rewritten + spelled count + signature")
    a = ap.parse_args()
    print(build_format_dataset(a.out_dir, n_train=a.n_train, n_val=a.n_val, n_test=a.n_test, seed=a.seed,
                               hf_name=a.hf_name, conll_dir=a.conll_dir, variant=a.variant,
                               min_entities=a.min_entities))


if __name__ == "__main__":  # python -m lorasub.data.format OUT_DIR [--n_train 5000] [--conll_dir DIR]
    main()


def metric_version() -> str:
    """Digest of the source of `check_alien` AND of every module-level function it calls.

    A hand-maintained version number is the thing that gets forgotten: the checker was hardened on
    11/09 to require sorted lists, and nothing in any output recorded which definition scored a run.
    The question was only closed because `format_order_ok` happened to exist — by luck, not design.
    Hashing the source cannot lie: change the logic, the digest changes, and `_refuse_if_mixed` stops
    the paper tables from averaging two definitions of the same metric.

    THE TRANSITIVE CLOSURE MATTERS. `check_alien` delegates to `signature`, `spell_number` and the
    three `_f1*` helpers. Hashing only `check_alien` would let a change to how initials are built, or
    to how counts are spelled, alter the metric while leaving the digest untouched — the exact failure
    this field exists to prevent, one call deep. The closure is walked from the AST, so a helper added
    later is picked up without anyone remembering to update a list.

    Normalised for whitespace and comments, so reformatting does not invalidate a campaign while any
    change to the logic does.
    """
    import ast
    import hashlib
    import inspect
    import re
    import sys

    module = sys.modules[__name__]
    top_level = {n.name for n in ast.parse(inspect.getsource(module)).body
                 if isinstance(n, ast.FunctionDef)}

    def called_by(fn_name: str) -> set[str]:
        tree = ast.parse(textwrap.dedent(inspect.getsource(getattr(module, fn_name))))
        return {n.func.id for n in ast.walk(tree)
                if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)} & top_level

    import textwrap
    seen: set[str] = set()
    stack = ["check_alien"]
    while stack:                                   # transitive closure, helpers of helpers included
        name = stack.pop()
        if name in seen:
            continue
        seen.add(name)
        stack.extend(called_by(name) - seen)

    chunks = []
    for name in sorted(seen):                      # sorted: the digest must not depend on walk order
        src = inspect.getsource(getattr(module, name))
        src = re.sub(r'#.*', '', src)                        # comments
        src = re.sub(r'(""".*?"""|\'\'\'.*?\'\'\')', '', src, flags=re.S)   # docstrings
        src = re.sub(r'\s+', ' ', src).strip()               # whitespace
        chunks.append(f"{name}:{src}")
    return hashlib.blake2b("\n".join(chunks).encode(), digest_size=6).hexdigest()
